version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 5
    groups:
      development-routine:
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      production-resolutions:
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: jest-matcher-utils
        update-types:
          - version-update:semver-major
      - dependency-name: openai
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
