import { Example } from '../types/examples.js';

export const defaultExamples: Example[] = [
  {
    content: 'I need to pick up bananas and bread.',
    assertion: 'mention a fruit',
    assessment: 'Mentions bananas',
    pass: true,
  },
  {
    content: 'This is absolutely awful!!',
    assertion: 'be positive',
    assessment: 'Contains negative sentiment',
    pass: false,
  },
  {
    content: 'Circles, squares, and triangles.',
    assertion: 'not mention colors',
    assessment: 'Does not mention colors',
    pass: true,
  },
  {
    content: 'Bonjour le monde.',
    assertion: 'be in English',
    assessment: 'Is in French',
    pass: false,
  },
  {
    content: 'Bonjour le monde.',
    assertion: 'be in French',
    assessment: 'Is in French',
    pass: true,
  },
  {
    content: "Hello, I'm a programmer. I love TypeScript!",
    assertion: 'be one sentence',
    assessment: 'Is two sentences',
    pass: false,
  },
  {
    content: 'Unit testing is awesome.',
    assertion: 'be three sentences',
    assessment: 'Is one sentence',
    pass: false,
  },
  {
    content: 'Yellow',
    assertion: 'be a color',
    assessment: 'Is a color',
    pass: true,
  },
  {
    content: 'The ball is round',
    assertion: 'include a shape',
    assessment: 'Includes round',
    pass: true,
  },
  {
    content: 'This is great!',
    assertion: 'be a color',
    assessment: 'Is not a color',
    pass: false,
  },
  {
    content: 'You did great!',
    assertion: 'be a compliment',
    assessment: 'Is a compliment',
    pass: true,
  },
  {
    content: 'That was terrible...',
    assertion: 'be a compliment',
    assessment: 'Is a criticism',
    pass: false,
  },
  {
    content: 'I look up to you',
    assertion: 'be an expression of admiration',
    assessment: 'Is an expression of admiration',
    pass: true,
  },
  {
    content: 'Ahoy, matey!',
    assertion: 'sound like a pirate',
    assessment: 'Sounds like a pirate',
    pass: true,
  },
  {
    content: 'Beep boop beep boop',
    assertion: 'sound like a human',
    assessment: 'Sounds like a robot',
    pass: false,
  },
  {
    content: 'Bonjour',
    assertion: 'use Spanish',
    assessment: 'Includes "Boujour"',
    pass: false,
  },
  {
    content: 'Quantum entanglement',
    assertion: 'be about biology',
    assessment: 'Is about physics',
    pass: false,
  },
  {
    content: 'Inflation',
    assertion: 'be about economics',
    assessment: 'Mentions inflation',
    pass: true,
  },
  {
    content:
      'I was kind of thinking about maybe some day considering running for major.',
    assertion: 'be concise',
    assessment: 'Is verbose',
    pass: false,
  },
  {
    content: 'A',
    assertion: 'use a full sentence',
    assessment: 'Is only one word',
    pass: false,
  },
  {
    content: 'I went to the store.',
    assertion: 'use a full sentence',
    assessment: 'Is a full sentence',
    pass: true,
  },
  {
    content: 'Purple is a shape',
    assertion: 'be accurate',
    assessment: 'Purple is not a shape',
    pass: false,
  },
  {
    content: 'The sky is blue',
    assertion: 'be accurate',
    assessment: 'The sky is blue',
    pass: true,
  },
  {
    content: 'The sky is blue',
    assertion: 'be inaccurate',
    assessment: 'The sky is blue',
    pass: false,
  },
  {
    content: 'The sun is bright',
    assertion: 'mention the moon',
    assessment: 'Does not mention the moon',
    pass: false,
  },
  {
    content: 'Bananas are yellow',
    assertion: 'mention bananas',
    assessment: 'Mentions bananas',
    pass: true,
  },
  {
    content: 'The water is blue',
    assertion: 'mention the sky',
    assessment: 'Only mentions water',
    pass: false,
  },
  {
    content: 'One, two, three',
    assertion: 'get to four',
    assessment: 'Stops at three',
    pass: false,
  },
  {
    content: 'One, two, three, four, five',
    assertion: 'get to at least four',
    assessment: 'Gets to five',
    pass: true,
  },
  {
    content: "Let's fly to Mars!",
    assertion: 'mention two planets',
    assessment: 'Only mentions one planet',
    pass: false,
  },
  {
    content: 'Bonjour le monde.',
    assertion: 'use Spanish',
    assessment: 'Uses French',
    pass: false,
  },
  {
    content: "Hey what's up?",
    assertion: 'be casual',
    assessment: 'Is casual',
    pass: true,
  },
  {
    content: "Hey what's up?",
    assertion: 'be professional',
    assessment: 'Is casual',
    pass: false,
  },
];
